# Generated by Django 4.1.7 on 2023-03-22 16:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_author_slug_alter_book_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="authors",
            field=models.ManyToManyField(
                blank=True, related_name="book_list", to="core.author"
            ),
        ),
    ]
